# Generated by Django 3.1.7 on 2021-05-16 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diploma_app', '0002_auto_20210516_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomas',
            name='point',
            field=models.IntegerField(),
        ),
    ]
